apiVersion: v2
appVersion: 0.1.1
description: A Helm chart to deploy the Capsule Operator for easily implementing,
  managing, and maintaining mutitenancy and access control in Kubernetes.
home: https://github.com/clastix/capsule
icon: https://github.com/clastix/capsule/raw/master/assets/logo/capsule_small.png
keywords:
- kubernetes
- operator
- multi-tenancy
- multi-tenant
- multitenancy
- multitenant
- namespace
maintainers:
- email: hello@clastix.io
  name: Clastix Labs Team
name: capsule
sources:
- https://github.com/clastix/capsule
type: application
version: 0.1.6
