apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
