apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../../../manifests/kubeedge/cloudcore

secretGenerator:
  - name: kubeedge-certs
    files:
      - server.crt=.certs/server.crt
      - server.key=.certs/server.key

patchesJSON6902:
  - target:
      version: v1
      kind: Service
      name: cloudcore
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
