apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../../../manifests/kubeedge/cloudcore

secretGenerator:
  - name: kubeedge-certs
    files:
      - server.crt=.certs/server.cert
      - server.key=.certs/server.key
