name: Release

on:
  workflow_run:
    workflows: ["Lint Commit Messages"]
    branches:
      - main
      - beta
    types:
      - completed

jobs:
  on-success:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
